# 文件路径：.github/workflows/download-and-upload.yml
name: Download and Upload Files

on:
  push:
  # 监控 link.txt 文件的变化
  # 也可以监控整个目录的变化
  # paths:
  #   - 'AutoDown/**'

jobs:
  download-and-process:
    runs-on: ubuntu-latest # 使用最新的 Ubuntu 虚拟机

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Download link.txt
      run: |
        # 下载原始文件
        curl -L -o link.txt https://raw.githubusercontent.com/qinjunhaocn/AutoDown/main/link.txt
        # 查看文件内容
        cat link.txt

    - name: Read and Download Links
      run: |
        # 读取 link.txt 文件中的链接并下载
        # 假设 link.txt 中的链接是每行一个
        while IFS= read -r line; do
          # 检查是否是有效的链接
          if [[ "$line" =~ ^https?:// ]]; then
            # 使用 wget 下载链接内容到 artifacts 文件夹
            wget -P artifacts/ "$line"
          fi
        done < link.txt

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: downloaded-files # 上传产物的名称
        path: artifacts/ # 产物的路径
